import { WardrobeItem, RunwayTheme, JudgeProfile, AvatarState } from './types';

export const DEFAULT_AVATAR_STATE: AvatarState = {
  skin: 'peach',
  eyeColor: 'hazel',
  lipColor: 'rose',
  blushColor: '#f43f5e',
  hairStyle: 'hair_glam_waves',
  hairColor: 'honey',
  topId: 'top_corset_satin',
  bottomId: 'bottom_satin_pants',
  dressId: undefined,
  outerwearId: 'outer_fur_stole',
  shoesId: 'shoes_stiletto_glam',
  accessoryIds: ['acc_diamond_choker', 'acc_crystal_earrings'],
  wingsId: undefined,
  petId: 'pet_pomeranian',
  pose: 'model_classic',
  expression: 'smile',
};

export const WARDROBE_ITEMS: WardrobeItem[] = [
  // --- HAIRSTYLES ---
  {
    id: 'hair_glam_waves',
    name: 'Hollywood Glam Waves',
    category: 'hair',
    tags: ['glamour', 'haute_couture', 'classic', 'met_gala'],
    color: '#d4af37',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '✨',
    rarity: 'common',
    designKey: 'glam_waves',
  },
  {
    id: 'hair_cyber_bob',
    name: 'Neon Cyberpunk Bob',
    category: 'hair',
    tags: ['cyber', 'futuristic', 'y2k', 'edgy'],
    color: '#06b6d4',
    price: 250,
    currency: 'coins',
    isOwned: true,
    icon: '⚡',
    rarity: 'rare',
    designKey: 'cyber_bob',
  },
  {
    id: 'hair_twin_braids',
    name: 'K-Pop Idol Braids',
    category: 'hair',
    tags: ['y2k', 'kpop', 'cute', 'streetwear'],
    color: '#ec4899',
    price: 350,
    currency: 'coins',
    isOwned: true,
    icon: '🎀',
    rarity: 'rare',
    designKey: 'twin_braids',
  },
  {
    id: 'hair_high_ponytail',
    name: 'Snatched High Pony',
    category: 'hair',
    tags: ['glamour', 'chic', 'runway', 'met_gala'],
    color: '#1e293b',
    price: 500,
    currency: 'coins',
    isOwned: false,
    icon: '👑',
    rarity: 'luxury',
    designKey: 'high_ponytail',
  },
  {
    id: 'hair_fairy_curls',
    name: 'Ethereal Fairy Blossom Curls',
    category: 'hair',
    tags: ['fairy', 'pastel', 'ethereal', 'romantic'],
    color: '#e879f9',
    price: 80,
    currency: 'gems',
    isOwned: false,
    icon: '🌸',
    rarity: 'exclusive',
    designKey: 'fairy_curls',
  },
  {
    id: 'hair_sleek_straight',
    name: 'Silky Ultra-Long Straight',
    category: 'hair',
    tags: ['classic', 'old_money', 'chic', 'minimalist'],
    color: '#0f172a',
    price: 300,
    currency: 'coins',
    isOwned: true,
    icon: '💎',
    rarity: 'common',
    designKey: 'sleek_straight',
  },

  // --- TOPS ---
  {
    id: 'top_corset_satin',
    name: 'Embroidered Satin Corset',
    category: 'tops',
    tags: ['glamour', 'met_gala', 'haute_couture'],
    color: '#fb7185',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '🩱',
    rarity: 'common',
    designKey: 'corset_satin',
  },
  {
    id: 'top_cyber_crop',
    name: 'Holographic Cyber Crop Top',
    category: 'tops',
    tags: ['cyber', 'futuristic', 'y2k', 'neon'],
    color: '#00f0ff',
    price: 320,
    currency: 'coins',
    isOwned: true,
    icon: '🌐',
    rarity: 'rare',
    designKey: 'cyber_crop',
  },
  {
    id: 'top_butterfly_y2k',
    name: 'Sparkle Butterfly Camisole',
    category: 'tops',
    tags: ['y2k', 'kpop', 'vibrant', 'streetwear'],
    color: '#a855f7',
    price: 280,
    currency: 'coins',
    isOwned: true,
    icon: '🦋',
    rarity: 'rare',
    designKey: 'butterfly_top',
  },
  {
    id: 'top_silk_blouse',
    name: 'Pearl Silk Drape Blouse',
    category: 'tops',
    tags: ['old_money', 'classic', 'elegant', 'chic'],
    color: '#f8fafc',
    price: 450,
    currency: 'coins',
    isOwned: false,
    icon: '🤍',
    rarity: 'luxury',
    designKey: 'silk_blouse',
  },
  {
    id: 'top_fairy_corset',
    name: 'Flora Petal Corset',
    category: 'tops',
    tags: ['fairy', 'pastel', 'ethereal', 'floral'],
    color: '#86efac',
    price: 50,
    currency: 'gems',
    isOwned: false,
    icon: '🍃',
    rarity: 'exclusive',
    designKey: 'fairy_corset',
  },

  // --- BOTTOMS ---
  {
    id: 'bottom_satin_pants',
    name: 'High-Waist Satin Trousers',
    category: 'bottoms',
    tags: ['glamour', 'chic', 'classic', 'met_gala'],
    color: '#f43f5e',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '👖',
    rarity: 'common',
    designKey: 'satin_pants',
  },
  {
    id: 'bottom_tennis_skirt',
    name: 'Pleated Y2K Tennis Skirt',
    category: 'bottoms',
    tags: ['y2k', 'kpop', 'cute', 'streetwear'],
    color: '#e2e8f0',
    price: 260,
    currency: 'coins',
    isOwned: true,
    icon: '👗',
    rarity: 'common',
    designKey: 'tennis_skirt',
  },
  {
    id: 'bottom_cyber_cargo',
    name: 'Neon Techwear Cyber Cargos',
    category: 'bottoms',
    tags: ['cyber', 'edgy', 'futuristic', 'neon'],
    color: '#0f172a',
    price: 380,
    currency: 'coins',
    isOwned: true,
    icon: '⚡',
    rarity: 'rare',
    designKey: 'cyber_cargo',
  },
  {
    id: 'bottom_leather_skirt',
    name: 'Buckled Moto Mini Skirt',
    category: 'bottoms',
    tags: ['edgy', 'cyber', 'rockstar', 'glamour'],
    color: '#18181b',
    price: 420,
    currency: 'coins',
    isOwned: false,
    icon: '🖤',
    rarity: 'luxury',
    designKey: 'leather_mini',
  },
  {
    id: 'bottom_fairy_tulle',
    name: 'Enchanted Tulle Tier Skirt',
    category: 'bottoms',
    tags: ['fairy', 'ethereal', 'pastel', 'romantic'],
    color: '#fbcfe8',
    price: 60,
    currency: 'gems',
    isOwned: false,
    icon: '🩰',
    rarity: 'exclusive',
    designKey: 'fairy_tulle',
  },

  // --- DRESSES & GOWNS ---
  {
    id: 'dress_crystal_slip',
    name: 'Met Gala Diamond Crystal Gown',
    category: 'dresses',
    tags: ['glamour', 'met_gala', 'haute_couture', 'luxury'],
    color: '#e0e7ff',
    price: 750,
    currency: 'coins',
    isOwned: false,
    icon: '✨',
    rarity: 'luxury',
    designKey: 'crystal_gown',
  },
  {
    id: 'dress_y2k_metallic',
    name: 'Molten Silver Y2K Halter Mini',
    category: 'dresses',
    tags: ['y2k', 'cyber', 'kpop', 'party'],
    color: '#cbd5e1',
    price: 480,
    currency: 'coins',
    isOwned: false,
    icon: '🪩',
    rarity: 'rare',
    designKey: 'metallic_mini',
  },
  {
    id: 'dress_fairy_aurora',
    name: 'Celestial Aurora Fairy Gown',
    category: 'dresses',
    tags: ['fairy', 'ethereal', 'haute_couture', 'pastel'],
    color: '#c084fc',
    price: 120,
    currency: 'gems',
    isOwned: false,
    icon: '🧚‍♀️',
    rarity: 'exclusive',
    designKey: 'fairy_gown',
  },
  {
    id: 'dress_red_carpet_slit',
    name: 'Crimson Velvet High-Slit Gown',
    category: 'dresses',
    tags: ['glamour', 'met_gala', 'old_money', 'classic'],
    color: '#be123c',
    price: 600,
    currency: 'coins',
    isOwned: false,
    icon: '💃',
    rarity: 'luxury',
    designKey: 'red_slit_gown',
  },

  // --- OUTERWEAR ---
  {
    id: 'outer_fur_stole',
    name: 'Plush Faux Fur Glamour Stole',
    category: 'outerwear',
    tags: ['glamour', 'met_gala', 'old_money', 'winter'],
    color: '#f8fafc',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '🧣',
    rarity: 'common',
    designKey: 'fur_stole',
  },
  {
    id: 'outer_leather_moto',
    name: 'Cropped Cyber Moto Jacket',
    category: 'outerwear',
    tags: ['cyber', 'edgy', 'streetwear', 'y2k'],
    color: '#1e1b4b',
    price: 360,
    currency: 'coins',
    isOwned: true,
    icon: '🧥',
    rarity: 'rare',
    designKey: 'leather_moto',
  },
  {
    id: 'outer_tweed_blazer',
    name: 'French Chic Bouclé Blazer',
    category: 'outerwear',
    tags: ['old_money', 'classic', 'chic', 'luxury'],
    color: '#fed7aa',
    price: 520,
    currency: 'coins',
    isOwned: false,
    icon: '👑',
    rarity: 'luxury',
    designKey: 'tweed_blazer',
  },

  // --- SHOES ---
  {
    id: 'shoes_stiletto_glam',
    name: 'Diamond Ankle-Wrap Stilettos',
    category: 'shoes',
    tags: ['glamour', 'met_gala', 'chic', 'classic'],
    color: '#fb7185',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '👠',
    rarity: 'common',
    designKey: 'stiletto_glam',
  },
  {
    id: 'shoes_cyber_boots',
    name: 'Platform Neon Knee-High Boots',
    category: 'shoes',
    tags: ['cyber', 'futuristic', 'y2k', 'edgy'],
    color: '#06b6d4',
    price: 290,
    currency: 'coins',
    isOwned: true,
    icon: '👢',
    rarity: 'rare',
    designKey: 'cyber_boots',
  },
  {
    id: 'shoes_chunky_sneakers',
    name: 'Chunky Cloud Platform Sneakers',
    category: 'shoes',
    tags: ['y2k', 'kpop', 'streetwear', 'casual'],
    color: '#f43f5e',
    price: 240,
    currency: 'coins',
    isOwned: true,
    icon: '👟',
    rarity: 'common',
    designKey: 'cloud_sneakers',
  },
  {
    id: 'shoes_glass_slippers',
    name: 'Cinderella Crystal Platforms',
    category: 'shoes',
    tags: ['fairy', 'glamour', 'haute_couture'],
    color: '#bae6fd',
    price: 70,
    currency: 'gems',
    isOwned: false,
    icon: '✨',
    rarity: 'exclusive',
    designKey: 'glass_slippers',
  },

  // --- ACCESSORIES ---
  {
    id: 'acc_diamond_choker',
    name: 'Cascading Diamond Tennis Choker',
    category: 'accessories',
    tags: ['glamour', 'met_gala', 'haute_couture', 'old_money'],
    color: '#e0e7ff',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '💎',
    rarity: 'common',
    designKey: 'diamond_choker',
  },
  {
    id: 'acc_crystal_earrings',
    name: 'Chandelier Crystal Drop Earrings',
    category: 'accessories',
    tags: ['glamour', 'met_gala', 'classic'],
    color: '#f8fafc',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '⭐',
    rarity: 'common',
    designKey: 'crystal_earrings',
  },
  {
    id: 'acc_cyber_visor',
    name: 'Holographic Cyber HUD Shades',
    category: 'accessories',
    tags: ['cyber', 'futuristic', 'neon'],
    color: '#00f0ff',
    price: 220,
    currency: 'coins',
    isOwned: true,
    icon: '🕶️',
    rarity: 'rare',
    designKey: 'cyber_visor',
  },
  {
    id: 'acc_designer_bag',
    name: 'Micro Quilted Gold Chain Bag',
    category: 'accessories',
    tags: ['old_money', 'glamour', 'chic', 'y2k'],
    color: '#f43f5e',
    price: 450,
    currency: 'coins',
    isOwned: false,
    icon: '👜',
    rarity: 'luxury',
    designKey: 'designer_bag',
  },
  {
    id: 'acc_tiara_royal',
    name: 'Imperial Platinum Tiara',
    category: 'accessories',
    tags: ['met_gala', 'haute_couture', 'fairy', 'old_money'],
    color: '#f8fafc',
    price: 90,
    currency: 'gems',
    isOwned: false,
    icon: '👑',
    rarity: 'exclusive',
    designKey: 'royal_tiara',
  },

  // --- WINGS ---
  {
    id: 'wings_fairy_gossamer',
    name: 'Gossamer Iridescent Fairy Wings',
    category: 'wings',
    tags: ['fairy', 'ethereal', 'fantasy'],
    color: '#f0abfc',
    price: 100,
    currency: 'gems',
    isOwned: false,
    icon: '🪽',
    rarity: 'exclusive',
    designKey: 'fairy_wings',
  },
  {
    id: 'wings_cyber_energy',
    name: 'Neon Plasma Cyber Thruster Wings',
    category: 'wings',
    tags: ['cyber', 'futuristic', 'neon'],
    color: '#00f0ff',
    price: 650,
    currency: 'coins',
    isOwned: false,
    icon: '⚡',
    rarity: 'luxury',
    designKey: 'cyber_wings',
  },

  // --- PETS ---
  {
    id: 'pet_pomeranian',
    name: 'Chanel the Teacup Pomeranian',
    category: 'pets',
    tags: ['glamour', 'cute', 'chic', 'old_money'],
    color: '#ffedd5',
    price: 0,
    currency: 'coins',
    isOwned: true,
    icon: '🐕',
    rarity: 'common',
    designKey: 'teacup_pom',
  },
  {
    id: 'pet_cyber_kitty',
    name: 'Circuit the Robotic Hologram Kitty',
    category: 'pets',
    tags: ['cyber', 'futuristic', 'cute'],
    color: '#c084fc',
    price: 400,
    currency: 'coins',
    isOwned: false,
    icon: '🐱',
    rarity: 'rare',
    designKey: 'cyber_cat',
  },
  {
    id: 'pet_cloud_bunny',
    name: 'Mochi the Fluffy Lop Bunny',
    category: 'pets',
    tags: ['fairy', 'cute', 'pastel'],
    color: '#fdf2f8',
    price: 50,
    currency: 'gems',
    isOwned: false,
    icon: '🐰',
    rarity: 'exclusive',
    designKey: 'fluffy_bunny',
  },
];

export const RUNWAY_THEMES: RunwayTheme[] = [
  {
    id: 'theme_met_gala',
    name: 'Met Gala Haute Couture',
    subtitle: 'Diamonds, Dramatic Silhouettes & Red Carpet Royalty',
    description: 'Style a breathtaking, head-turning red carpet masterpiece adorned with crystals, satin, and pure star power.',
    requiredTags: ['glamour', 'met_gala'],
    bonusTags: ['haute_couture', 'luxury', 'old_money'],
    backdrop: 'met_gala_carpet',
    minScoreToPass: 70,
    rewardCoins: 350,
    rewardGems: 15,
  },
  {
    id: 'theme_cyberpunk',
    name: 'Neon Cyberpunk Underground',
    subtitle: 'High Tech, Holographics & Futuristic Edginess',
    description: 'Walk the neon-drenched runway of Neo-Tokyo. Layer holographic techwear, cyber visors, and electric hues.',
    requiredTags: ['cyber'],
    bonusTags: ['futuristic', 'neon', 'edgy'],
    backdrop: 'cyber_nightclub',
    minScoreToPass: 68,
    rewardCoins: 300,
    rewardGems: 12,
  },
  {
    id: 'theme_y2k_pop',
    name: 'Y2K Pop Star World Tour',
    subtitle: 'Early 2000s Metallics, Butterfly Tops & Street Glam',
    description: 'Step into the music video set with chunky platforms, butterfly motifs, and iconic nostalgic pop flair.',
    requiredTags: ['y2k'],
    bonusTags: ['kpop', 'streetwear', 'vibrant'],
    backdrop: 'y2k_stage',
    minScoreToPass: 70,
    rewardCoins: 280,
    rewardGems: 10,
  },
  {
    id: 'theme_fairycore',
    name: 'Enchanted Fairycore Grove',
    subtitle: 'Pastel Florals, Gossamer Tulle & Forest Magic',
    description: 'Channel your inner ethereal fairy queen with delicate gossamer silks, petal tiers, and mystical charms.',
    requiredTags: ['fairy'],
    bonusTags: ['ethereal', 'pastel', 'floral'],
    backdrop: 'fairy_garden',
    minScoreToPass: 72,
    rewardCoins: 320,
    rewardGems: 15,
  },
  {
    id: 'theme_old_money',
    name: 'Monaco Riviera Old Money',
    subtitle: 'Quiet Luxury, Bouclé Blazers & Understated Elegance',
    description: 'Exude timeless heritage sophistication. Pair tailored tweed, silk blouses, and pearl accents for elite status.',
    requiredTags: ['old_money'],
    bonusTags: ['classic', 'chic', 'elegant'],
    backdrop: 'monaco_villa',
    minScoreToPass: 75,
    rewardCoins: 400,
    rewardGems: 20,
  },
];

export const CELEBRITY_JUDGES: JudgeProfile[] = [
  {
    name: 'Aria Vance',
    title: 'Editor-in-Chief, Vogue Metaverse',
    avatar: '👠',
    quote: 'True style is unmistakable. I demand silhouette balance and immaculate accessorizing.',
    criteria: 'Favors Haute Couture, Layering, and Silhouette Harmony',
  },
  {
    name: 'Leo Fontaine',
    title: 'Paris Runway Creative Director',
    avatar: '🕶️',
    quote: 'If your outfit doesn’t make an entrance, you might as well stay in the dressing room, darling.',
    criteria: 'Rewards Bold Theme Accuracy and High-Impact Accessories',
  },
  {
    name: 'K-Nova',
    title: 'Global Pop Idol & Trendsetter',
    avatar: '💖',
    quote: 'Omo! I look for stage presence, sparkle, and that it-factor that makes fans scream!',
    criteria: 'Loves Sparkle, Poses, Hair Colors, and Pet Companions',
  },
];
